name: quantem-widget-release
channels:
  - conda-forge
dependencies:
  - python=3.11
  - anywidget>=0.9.0
  - colorspacious
  - dill
  - hatchling
  - h5py>=3.13.0
  - matplotlib
  - numpy>=2.0
  - pillow>=10.0.0
  - pip
  - pytest
  - python-build
  - pytorch>=2.7.0
  - pyyaml
  - scipy
  - tqdm
  - traitlets>=5.0.0
  - twine
  - zarr>=3.0
